[pytest]
minversion = 7.0
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --strict-markers
    --reruns 1
    --alluredir=./reports/allure-results
    --clean-alluredir
markers =
    smoke: 冒烟测试用例
    permission: 权限测试用例
    order_flow: 下单业务流场景
    regression: 回归测试用例
    slow: 运行时间较长的用例
